---INSERT INTO TABLE 
--INSERT INTO [Books] ([BookName],[Description],[Author])
--VALUES ('Harry','Potter','English')



-----INSERT DATA INTO TABLE FROM SELECT QUERY
--INSERT INTO PERSONS (id,person_name,birth_date,phone,email)
--SELECT BookId,BookName,NULL,'NA','NA'
--FROM Books 





----UPDATE THE TABLE ROW
UPDATE PERSONS
SET email='WEBAPI@GMAIL.COM'
WHERE ID=1

--UPDATE PHONE TO 11111 TO IDNUMBER 2

UPDATE PERSONS
SET PHONE='111111',birth_date=GETDATE()
WHERE ID=2



SELECT * FROM PERSONS

---DELETE DATA ROM TABLE

DELETE FROM PERSONS--- ONLY THIS WILL DELETE ALL DATA
WHERE ID=2
